spring.application.name=isobar-backend
#URl
api.bands.url=https://bands-api.vercel.app/api/bands
#Cache
spring.cache.type=simple
# Muda o caminho do Swagger UI
springdoc.swagger-ui.path=/docs
# Garante que os métodos da interface sejam lidos corretamente
springdoc.override-with-generic-response=true